### ISSUE TITLE
Display object

### ISSUE THREAD

**Issue by adamscao** [ArtemVeremienko/skype-parser#1]
Thank you for your work!

The media files in media directory cannot display correctly, could you please fix it?

**Comment by ArtemVeremienko** [comment]
I need to know your images name in **media** folder
For example my images:
![image](https://user-images.githubusercontent.com/36508702/76806426-0ad59880-67ea-11ea-88da-8e7dbadb2716.png)

**Comment by ArtemVeremienko** [comment]
Check the new version `index.html` for your media folder

**Comment by adamscao** [comment]
Great work! Thank you very much!
