### ISSUE TITLE
not displayed full conversation

### ISSUE THREAD

**Issue by bosugigi** [ArtemVeremienko/skype-parser#3]
Hi Artem Veremienko, me have aproblem when use your tool, it does not display full history (the last message is from 6/30/2020 but it just display to 12/06/2019) Me tried skype's original paser and it loaded full conversation. Please help, thank you in advance and sorry for my English...

![Capture](https://user-images.githubusercontent.com/67618786/86084886-1ebab700-bac8-11ea-9db5-7a1aa541469e.PNG)

**Comment by ArtemVeremienko** [comment]
Hi, @bosugigi
What browser did you use?
After download all message press Ctrl+Shift+I go to Console tab and send me log or screenshot.

**Comment by bosugigi** [comment]
Hi @ArtemVeremienko 
Me used Google Chrome,
Here the error message in Console: (I also attached a screenshot)

main.min.js:1 Uncaught TypeError: Cannot read property '0' of null
    at HTMLAnchorElement.t (main.min.js:1)

![Capture](https://user-images.githubusercontent.com/67618786/86196247-0c4e8500-bb7d-11ea-94b1-fa95ede44647.PNG)

**Comment by bosugigi** [comment]
Me can sent you the "messages.json" to your email if you want it. Thank you!

**Comment by bosugigi** [comment]
Me tried Chrome, Firefox, M$ Edge, all latest versions, same error. FYI, thank you very much

**Comment by ArtemVeremienko** [comment]
> Me can sent you the "messages.json" to your email if you want it. Thank you! 

This will be better and faster. If you can, send me.
Email: temaspsxxx@gmail.com

**Comment by bosugigi** [comment]
> > Me can sent you the "messages.json" to your email if you want it. Thank you!
> 
> This will be better and faster. If you can, send me.
> Email: [temaspsxxx@gmail.com](mailto:temaspsxxx@gmail.com)

Hi, me sent you, thank you in advance!

**Comment by ArtemVeremienko** [comment]
This error fixed. Download and try updated version.

**Comment by ArtemVeremienko** [comment]
I create **Release** for simpler use. Try it from here:
https://github.com/ArtemVeremienko/skype-parser/releases/

**Comment by bosugigi** [comment]
> This error fixed. Download and try updated version.

Work like charm!!!
Thank you very much!!
