### ISSUE TITLE
Full conversation not displayed

### ISSUE THREAD

**Issue by domineus1** [ArtemVeremienko/skype-parser#5]
Hi

Thanks for the tool to improve something Skype should've done natively :)

I am experiencing the same issue as previously reported in the following URL:

https://github.com/ArtemVeremienko/skype-parser/issues/3

There's currently 30,415 messages however, the messages displayed stop at the start of the file (screenshot below).

When I review the console in google chrome, I see this error 
Uncaught TypeError: Cannot read property '0' of null
    at HTMLAnchorElement.t (main.js:1)

I can provide the messages.json as well.

Thanks for the great tool!

<img width="1824" alt="Screen Shot 2020-07-30 at 2 15 00 PM" src="https://user-images.githubusercontent.com/54510508/88965499-78053a00-d270-11ea-8098-0d09cda82a54.png">

**Comment by ArtemVeremienko** [comment]
Hi @domineus1 !

If you can, send me your `messages.json`.

**Comment by domineus1** [comment]
Hi 

I sent via email. 

Thanks for reviewing

**Comment by ArtemVeremienko** [comment]
Fixed. Try now.

**Comment by domineus1** [comment]
Woo boo 

Works like a charm! Thank you so much for this. 

You rock!
